# Generated by Django 3.2 on 2021-09-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_rename_match_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='score',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
