# Generated by Django 3.2 on 2021-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('England', 'Англия'), ('Spain', 'Испания'), ('Germany', 'Германия'), ('France', 'Франция'), ('Italy', 'Италия'), ('Argentina', 'Аргентина'), ('Brazil', 'Бразилия'), ('Belgium', 'Бельгия'), ('Croatia', 'Хорватия'), ('Sweden', 'Швеция'), ('Portugal', 'Португалия')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='championship.league')),
            ],
        ),
    ]
