# Generated by Django 3.2 on 2021-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalteam',
            name='confederation',
            field=models.CharField(choices=[('UEFA', 'UEFA'), ('AFC', 'AFC'), ('CAF', 'CAF'), ('CONCACAF', 'CONCACAF'), ('CONMEBOL', 'CONMEBOL'), ('OFC', 'OFC')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
