# Generated by Django 3.2 on 2021-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField()),
                ('national_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.nationalteam')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='team.team')),
            ],
        ),
    ]
